#!/bin/bash

G="\033[1;32m"
R="\033[0;31m"
N="\033[0m"


mkdir data 
##### Generate files
echo "Generating random test files"
for i in `seq 10 -1 1`
do
    printf "\r\tGenerating test file [data/ucp_test$i.dat] ... "
    dd if=/dev/urandom of=data/ucp_test$i.dat bs=1M count=$i 2> /dev/null
done
echo ""

mkdir data/recurse
for i in `seq 10 -1 1`
do
    printf "\r\tGenerating test file [data/recurse/ucp_test$i.dat] ... "
    dd if=/dev/urandom of=data/recurse/ucp_test$i.dat bs=1M count=$i 2> /dev/null
done
echo ""

for k in `seq 0 100`
do
    clear
    echo "Test round #$k"

##### Transfer files
    echo -e "ucp *.dat localhost:/tmp/ucp_test"
    ucp data localhost:/tmp/ucp_test

##### Validate transfer
    echo "Validating transfer ..."
    for i in `seq 10 -1 1`
    do
        printf "\tTesting [data/ucp_test$i.dat] \t\t\t"
        diff data/ucp_test$i.dat           \
            /tmp/ucp_test/ucp_test$i.dat   \
            2> /dev/null > /dev/null
        stat=$?
        if [ $stat -ne 0 ]; then
            echo -e "[$R FAILED $N]"
            echo "test failed: [`data`] [ucp_test$i.dat] [test round #k]" >> test.log
        else
            echo -e "[$G PASSED $N]"
        fi
    done

    for i in `seq 10 -1 1`
    do
        printf "\tTesting [data/recurse/ucp_test$i.dat] \t\t"
        diff data/recurse/ucp_test$i.dat           \
            /tmp/ucp_test/recurse/ucp_test$i.dat   \
            2> /dev/null > /dev/null
        stat=$?
        if [ $stat -ne 0 ]; then
            echo -e "[$R FAILED $N]"
            echo "test failed: [`data`] [recurse/ucp_test$i.dat] [test round #k]" >> test.log
        else
            echo -e "[$G PASSED $N]"
        fi
    done


done


##### Cleaning test files
echo -e "\nCleaning test files ..."
echo -e "\trm -rf /tmp/ucp_tests"
rm -rf /tmp/ucp_tests
echo -e "\trm -rf data"
rm -rf data

